# Generated by Django 5.0.3 on 2024-04-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgWeb', '0002_remove_pathway_id_alter_pathway_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='graphInfo',
            field=models.JSONField(default={}),
        ),
    ]
