# Generated by Django 5.0.3 on 2024-04-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgWeb', '0004_alter_pathway_graphinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='graphInfo',
            field=models.TextField(),
        ),
    ]
